function [net,tr,target]=latentO2Delivery(trainData,trainComm,commorbidityNames,show)
%
%
% Returns a trained NN, training performance metrics, and generated target 
% for estimation of O2 Delivery

%Define the following variables as being indicative of an increase in O2
%demands
trueVar={'CONGESTIVE_HEART_FAILURE',...
    'CARDIAC_ARRHYTHMIAS',...
    'VALVULAR_DISEASE',...
    'BLOOD_LOSS_ANEMIA',...
    'COAGULOPATHY',...
    'DEFICIENCY_ANEMIAS',...
    'PEPTIC_ULCER',...
    'PERIPHERAL_VASCULAR',...
    'PULMONARY_CIRCULATION',...
    'RENAL_FAILURE'};

falseVar={};
[net,tr,target]=latentNet(trainData,trainComm,commorbidityNames,trueVar,falseVar,show);